[package]
name = "shell"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
thiserror = "2.0.6"
libc = "0.2"
dirs = "5.0.1"
chrono = "0.4"
users = "0.11"
term_size = "0.3"
rustyline = "15.0.0"
